### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by ainouss** [better-js-logging/angular-logger#15]
Sometimes its good to know what's taking so damn long; you can use Logger.time() and Logger.timeEnd() to keep tabs on things.
// Start timing something
Logger.time('self destruct sequence');

// ... Some time passes ...

// Stop timing something.
Logger.timeEnd('self destruct sequence'); // logs: 'self destruct sequence: 1022ms'.
I've created a pull request, I can work on it :) :)

**Comment by bbottema** [comment]
Thank you for your suggestion, but I don't think we should add this type of functionality. It pertains to _content_ you would log, not logging itself and as such I don't think it fits the library. Otherwise, where to draw the line, do we start adding formatting functions for dates, numbers, currency, time?
